### PR TITLE
Run #encode on ASCII-8BIT encoded log messages

### LINKED ISSUE #863: DecoratingLogger throws Encoding::UndefinedConversionError on ASCII-8BIT encoding
## Description
We're logging our requests with New Relic and had some issue with logging PayPal request/response logs. They're in ASCII-8BIT encoding.

When calling `.to_json` on a message in `NewRelic::Agent::Logging::DecoratingFormatter#escape` it raises `Encoding::UndefinedConversionError: "\xC4" from ASCII-8BIT to UTF-8`

```
message = "č"

message.encoding
=> #<Encoding:UTF-8>

message.to_json
=> "\"č\""

message.force_encoding(Encoding::ASCII-8BIT).to_json
Encoding::UndefinedConversionError: "\xC4" from ASCII-8BIT to UTF-8
from /Users/user/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/core_ext/object/json.rb:40:in `to_json'
```

This issue is similar to #842.

## Expected Behavior
The behaviour should be as it's been solved in #844 by scrubbing these characters or by forcing the UTF-8 encoding.

```
message.force_encoding(Encoding::ASCII_8BIT).force_encoding(Encoding::UTF_8).to_json
=> "\"č\""
```

## Steps to Reproduce
If a message that is passed to `NewRelic::Agent::Logging::DecoratingFormatter#escape` is in `Encoding::ASCII_8BIT` it will raise an error when calling `.to_json` on it.

```
Rails.logger.info "č"
č

Rails.logger.info "č".force_encoding(Encoding::ASCII_8BIT)
č
Encoding::UndefinedConversionError: "\xC4" from ASCII-8BIT to UTF-8
from /Users/nika/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activesupport-6.1.4.1/lib/active_support/core_ext/object/json.rb:40:in `to_json'
```

## Your Environment
Ruby 2.6.1
Rails 6.1.4.1
New Relic - tried with 7.2.0 and current [master commit](https://github.com/newrelic/newrelic-ruby-agent/commit/a1a5fe17e1311cf6324c5513ed0c1f615466e730) (8.2.0-pre)

### PR DESCRIPTION
**Pull request by kaylareopelle**
_Before contributing, please read our [contributing guidelines](https://github.com/newrelic/newrelic-ruby-agent/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/newrelic/.github/blob/master/CODE_OF_CONDUCT.md)._

# Overview
* Update `NewRelic::Agent::Logging::DecoratingFormatter#escape` to use `String#encoding` instead of `String#scrub`.
* Include test case for `Encoding::ASCII_8BIT` written by @nikajukic
* Update condition to call `#encoding` to look for both `valid_encoding?` and `Encoding::UTF_8`

# Related Github Issue
Closes #863 

# Testing
The agent includes a suite of unit and functional tests which should be used to
verify your changes don't break existing functionality. These tests will run with 
Github Actions when a pull request is made. More details on running the tests locally can be found 
[here for our unit tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/README.md), 
and [here for our functional tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/multiverse/README.md).
For most contributions, it is strongly recommended to add additional tests which
exercise your changes. 

# Reviewer Checklist
- [ ] Perform code review
- [ ] Add performance label
- [ ] Perform appropriate level of performance testing
- [ ] Confirm all checks passed
- [ ] Add version label before acceptance

### CODE REVIEW

File: lib/new_relic/agent/logging.rb [hunk 1]
```diff
@@ -89,7 +89,14 @@ def add_key_value message, key, value
 
         def escape(message)
           message = message.to_s unless message.is_a?(String)
-          message = message.scrub(REPLACEMENT_CHAR) unless message.valid_encoding?
+          unless message.valid_encoding?
```
Comment (nikajukic) [inline lib/new_relic/agent/logging.rb:92]: As I mentioned in #863 this will not cover ASCII-8BIT encoding because it's still valid. 
```
"č".force_encoding(Encoding::ASCII_8BIT).valid_encoding?
=> true
```


Try adding this test case:
```
def test_to_replace_ascii_8bit_chars
  message = 'message with an ASCII-8BIT character'
  input = "#{message} #{"č".force_encoding(Encoding::ASCII_8BIT)}"
  expectation = "#{message} #{DecoratingFormatter::REPLACEMENT_CHAR}#{DecoratingFormatter::REPLACEMENT_CHAR}"
  logger = DecoratingLogger.new @output
  logger.info input
  assert_equal expectation, last_message['message']
end
```

This is intended behavior. It will replace ASCII-8BIT `č` with two replacement charachters because `č` consists of `"\xC4\x8D"` and each character is invalid in UTF-8 and should therefore be replaced.

File: test/new_relic/agent/logging_test.rb [hunk 2]
```diff
@@ -95,8 +95,17 @@ def test_to_replace_non_utf_8_chars
...
+
+        def test_to_replace_ascii_8bit_chars
+          message = 'message with an ASCII-8BIT character'
+          input = "#{message} #{"č".force_encoding(Encoding::ASCII_8BIT)}"
+          expectation = "#{message} #{DecoratingFormatter::REPLACEMENT_CHAR}#{DecoratingFormatter::REPLACEMENT_CHAR}"
+          logger = DecoratingLogger.new @output
+
+          logger.info input
+          assert_equal expectation, last_message['message']
         end
```
Comment (kaylareopelle) [inline test/new_relic/agent/logging_test.rb:109]: Thanks for the test, @nikajukic!

**Review by tannalynn — COMMENTED** [review]
Looks good! TY!
Only thing we should add is the changelog entry for this change.

**Review by tannalynn — DISMISSED** [review]
Looks great! Thanks for adding the changelog entry for this!

**Review by tannalynn — APPROVED** [review]
