### PR TITLE
Run active_record_pg suite in serial

### LINKED ISSUE #1979: Fix intermittent active_record_pg failure when running in Docker
The active_record_pg multiverse test suite intermittently fails when running in docker:
```
PG::ObjectInUse: ERROR:  database "multiverse_activerecord_7_0_4_3_3_1_4_ruby" is being accessed by other users
DETAIL:  There is 1 other session using the database.
Couldn't drop database 'multiverse_activerecord_7_0_4_3_3_1_4_ruby'
```

Let's get this fixed!

Related to #1962

### PR DESCRIPTION
**Pull request by hannahramadan**
The active_record_pg test suite intermittently fails when running in parallel due to multiple processes attempting to access/manipulate the same database. Running this suite in serial prevents this from occurring.

Closes #1979

### CODE REVIEW

File: test/multiverse/lib/multiverse/suite.rb [hunk 1]
```diff
@@ -413,8 +413,9 @@ def log_test_running_process
       puts yellow("Starting tests in child PID #{Process.pid} at #{Time.now}\n")
     end
 
+    # active_record_pg test suite runs in serial to prevent database conflicts
     def should_serialize?
-      ENV['SERIALIZE'] || debug
+      ENV['SERIALIZE'] || debug || self.directory.include?('active_record_pg')
```
Comment (fallwith) [inline test/multiverse/lib/multiverse/suite.rb:418]:
```suggestion
      # TODO: Devise a way for an individual suite to express that it doesn't support parallel
      ENV['SERIALIZE'] || debug || self.directory.include?('active_record_pg')
```

**Review by fallwith — CHANGES_REQUESTED** [review]

**Review by fallwith — APPROVED** [review]

**Review by kaylareopelle — APPROVED** [review]
