### PR TITLE
Fix unused variable warnings in unit tests

### LINKED ISSUE #2554: Fix unused variable warnings in unit tests
When I was running some tests locally for https://github.com/newrelic/newrelic-ruby-agent/pull/2546, I noticed we had a few "unused variable" warnings.

### PR DESCRIPTION
**Pull request by kaylareopelle**
When I was running some tests locally for #2546, I noticed we had a few "unused variable" warnings. This PR fixes those warnings.

Closes #2554

### CODE REVIEW

File: test/new_relic/agent/serverless_handler_test.rb [hunk 1]
```diff
@@ -276,10 +276,10 @@ def test_custom_attributes_arent_supported_when_serverless
         skip_unless_minitest5_or_above
 
         attrs = {cool_id: 'James', server: 'less', current_time: Time.now.to_s}
+        attribute_set_attempted = false
         tl_current_mock = Minitest::Mock.new
         tl_current_mock.expect :add_custom_attributes, -> { attribute_set_attempted = true }, [attrs]
```
Comment (kaylareopelle) [inline test/new_relic/agent/serverless_handler_test.rb:281]: The warning for this one said `attribute_set_attempted` was assigned, but never used, with the `mock.expect` line as the culprit. Defining the argument before the proc removed the warning.

**Review by fallwith — APPROVED** [review]
