### PR TITLE
resolve infinite recursion when airbrake is present

### LINKED ISSUE #510: `6.14.0` creates infinite recursion on "net request" with rack-mini-profiler present
^^ Provide a general summary of the issue in the title above. ^^ 

## Description
We use [`fastimage`](https://rubygems.org/gems/fastimage/versions/2.2.0) to check the type of image behind the image URLs input by user before saving them.
Example code would be something like:
```ruby
FastImage.type(
  "https://duckduckgo.com/assets/logo_homepage.alt.v108.svg",
  timeout: 5,
).nil?

```

## Expected Behavior
It should work without infinite recursion (`SystemStackError: stack level too deep`)

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
<details>

<summary>Error Backtrace</summary>

```
/usr/local/lib/ruby/gems/2.7.0/gems/addressable-2.7.0/lib/addressable/idna/pure.rb:305:in `hash'
/usr/local/lib/ruby/gems/2.7.0/gems/addressable-2.7.0/lib/addressable/idna/pure.rb:305:in `lookup_unicode_composition'
/usr/local/lib/ruby/gems/2.7.0/gems/addressable-2.7.0/lib/addressable/idna/pure.rb:215:in `unicode_compose_pair'
/usr/local/lib/ruby/gems/2.7.0/gems/addressable-2.7.0/lib/addressable/idna/pure.rb:153:in `block in unicode_compose'
/usr/local/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/core_ext/range/each.rb:9:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/core_ext/range/each.rb:9:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/addressable-2.7.0/lib/addressable/idna/pure.rb:149:in `unicode_compose'
/usr/local/lib/ruby/gems/2.7.0/gems/addressable-2.7.0/lib/addressable/idna/pure.rb:121:in `unicode_normalize_kc'
/usr/local/lib/ruby/gems/2.7.0/gems/addressable-2.7.0/lib/addressable/uri.rb:566:in `normalize_component'
/usr/local/lib/ruby/gems/2.7.0/gems/addressable-2.7.0/lib/addressable/uri.rb:1538:in `block in normalized_path'
/usr/local/lib/ruby/gems/2.7.0/gems/addressable-2.7.0/lib/addressable/uri.rb:1537:in `map'
/usr/local/lib/ruby/gems/2.7.0/gems/addressable-2.7.0/lib/addressable/uri.rb:1537:in `normalized_path'
/usr/local/lib/ruby/gems/2.7.0/gems/addressable-2.7.0/lib/addressable/uri.rb:2171:in `normalize'
/usr/local/lib/ruby/gems/2.7.0/gems/addressable-2.7.0/lib/addressable/uri.rb:2184:in `normalize!'
/usr/local/lib/ruby/gems/2.7.0/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/http_clients/uri_util.rb:35:in `parse_and_normalize_url'
/usr/local/lib/ruby/gems/2.7.0/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/http_clients/net_http_wrappers.rb:65:in `uri'
/usr/local/lib/ruby/gems/2.7.0/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/instrumentation/net_prepend.rb:45:in `request'
/usr/local/lib/ruby/gems/2.7.0/gems/rack-mini-profiler-2.2.0/lib/patches/net_patches.rb:19:in `block in request_with_mini_profiler'
/usr/local/lib/ruby/gems/2.7.0/gems/rack-mini-profiler-2.2.0/lib/mini_profiler/profiling_methods.rb:46:in `step'
/usr/local/lib/ruby/gems/2.7.0/gems/rack-mini-profiler-2.2.0/lib/patches/net_patches.rb:18:in `request_with_mini_profiler'
/usr/local/lib/ruby/gems/2.7.0/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/instrumentation/net_prepend.rb:57:in `block (2 levels) in request'
/usr/local/lib/ruby/gems/2.7.0/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/tracer.rb:371:in `capture_segment_error'
/usr/local/lib/ruby/gems/2.7.0/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/instrumentation/net_prepend.rb:56:in `block in request'
/usr/local/lib/ruby/gems/2.7.0/gems/newrelic_rpm-6.14.0/lib/new_relic/agent.rb:506:in `disable_all_tracing'
/usr/local/lib/ruby/gems/2.7.0/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/instrumentation/net_prepend.rb:55:in `request'
/usr/local/lib/ruby/gems/2.7.0/gems/rack-mini-profiler-2.2.0/lib/patches/net_patches.rb:19:in `block in request_with_mini_profiler'
/usr/local/lib/ruby/gems/2.7.0/gems/rack-mini-profiler-2.2.0/lib/mini_profiler/profiling_methods.rb:46:in `step'
/usr/local/lib/ruby/gems/2.7.0/gems/rack-mini-profiler-2.2.0/lib/patches/net_patches.rb:18:in `request_with_mini_profiler'
/usr/local/lib/ruby/gems/2.7.0/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/instrumentation/net_prepend.rb:57:in `block (2 levels) in request'
/usr/local/lib/ruby/gems/2.7.0/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/tracer.rb:371:in `capture_segment_error'
/usr/local/lib/ruby/gems/2.7.0/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/instrumentation/net_prepend.rb:56:in `block in request'
/usr/local/lib/ruby/gems/2.7.0/gems/newrelic_rpm-6.14.0/lib/new_relic/agent.rb:506:in `disable_all_tracing'
/usr/local/lib/ruby/gems/2.7.0/gems/newrelic_rpm-6.14.0/lib/new_relic/agent/instrumentation/net_prepend.rb:55:in `request'
/usr/local/lib/ruby/gems/2.7.0/gems/rack-mini-profiler-2.2.0/lib/patches/net_patches.rb:19:in `block in request_with_mini_profiler'
/usr/local/lib/ruby/gems/2.7.0/gems/rack-mini-profiler-2.2.0/lib/mini_profiler/profiling_methods.rb:46:in `step'
/usr/local/lib/ruby/gems/2.7.0/gems/rack-mini-profiler-2.2.0/lib/patches/net_patches.rb:18:in `request_with_mini_profiler'
```

</details>

## Steps to Reproduce
```ruby
begin
  parsed_uri = URI.parse("https://duckduckgo.com/assets/logo_homepage.alt.v108.svg")
  http = Net::HTTP.new(parsed_uri.host, parsed_uri.port)
  response = http.request_get(parsed_uri.request_uri, {'Accept-Encoding' => 'identity'})
  response.code
rescue SystemStackError => ex
  puts ex.backtrace
  raise
end

```

## Your Environment
Include as many relevant details about your environment as possible including the running version of the Ruby agent, the Ruby version being used and any other relevant environment information
- Docker with Ubuntu 18.04 LTS, same for Docker host
- Ruby `2.7.2`, Rails `6.0.3.4`
- `rack-mini-profiler (2.2.0)`
- `newrelic_rpm (6.14.0)`

## Additional context
`newrelic_rpm (6.13.1)` has no such issue
This can only be reproduced on production like environment
(This issue first affects production env & later reproduced on staging)

### PR DESCRIPTION
**Pull request by mwlang**
# Overview
resolves #510 where infinite recursion error occurs when both the Ruby agent and Airbrake are loaded in a Rails project.  Airbrake and the Ruby agent both are monkey patching the Net::HTTP#request method in order to benchmark.  When prepend method of patching is used, we end up with an infinite recursion issue since the two approaches cannot be used together.

# Related Github Issue
Closes #510

### CODE REVIEW

File: lib/new_relic/agent/instrumentation/net.rb [hunk 1]
```diff
@@ -15,75 +15,51 @@
     require 'new_relic/agent/http_clients/net_http_wrappers'
   end
 
+  def monkey_patched
+    defined?(::Airbrake) || 
+    defined?(::Rack::MiniProfiler) ||
+    source_location_for(Net::HTTP, "request") =~ /airbrake|profiler/i
```
Comment (tannalynn) [inline lib/new_relic/agent/instrumentation/net.rb:21]: Since we are doing this source check for airbrake, shouldn't we also be doing this for rack miniprofiler?

Comment (mwlang) [reply lib/new_relic/agent/instrumentation/net.rb:21]: we are....line 20....or am I missing something subtle in this question?

Comment (tannalynn) [reply lib/new_relic/agent/instrumentation/net.rb:21]: Oh yeah, you right, you right, it is totally there. lol I misread the regex and thought it was checking for "airbrake/profile", didn't realize it was |.

**Review by tannalynn — APPROVED** [review]
