### PR TITLE
browser monitoring injection logic hardening

### LINKED ISSUE #2462: browser_monitoring throws exception on non string HTTP header Content-Type
## Description

Found two problems in case the request HTTP header ContentType is Symbol,
then newrelic just produces exception: 

```
NoMethodError "undefined method `include?' for an instance of Symbol
```

## Expected Behavior

Newrelic should catch all exceptions with invalid headers and does not throw exception.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
Provide any other relevant log data.
TIP:  Scrub logs and diagnostic information for sensitive information

The line: https://github.com/newrelic/newrelic-ruby-agent/blob/414ddadeb103626a624727e36229dff811439f9a/lib/new_relic/rack/browser_monitoring.rb#L103

<details><summary>Backtrace</summary>
<p>

```
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.7.1/lib/new_relic/rack/browser_monitoring.rb:103:in `html?'
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.7.1/lib/new_relic/rack/browser_monitoring.rb:65:in `should_instrument?'
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.7.1/lib/new_relic/rack/browser_monitoring.rb:42:in `traced_call'
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.7.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/warden-jwt_auth-0.8.0/lib/warden/jwt_auth/middleware/token_dispatcher.rb:20:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.7.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/warden-jwt_auth-0.8.0/lib/warden/jwt_auth/middleware/revocation_manager.rb:21:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.7.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/rack-2.2.8.1/lib/rack/builder.rb:244:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/warden-jwt_auth-0.8.0/lib/warden/jwt_auth/middleware.rb:22:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.7.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
/app/vendor/bundle/ruby/3.3.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
/app/vendor/bundle/ruby/3.3.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.7.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/rack-2.2.8.1/lib/rack/tempfile_reaper.rb:15:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.7.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/rack-2.2.8.1/lib/rack/etag.rb:27:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.7.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/rack-2.2.8.1/lib/rack/conditional_get.rb:27:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.7.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/rack-2.2.8.1/lib/rack/head.rb:12:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.7.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.0.8.1/lib/action_dispatch/http/permissions_policy.rb:38:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.7.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
<truncated 43 additional frames>
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.7.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.7.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/static.rb:23:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.7.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/rack-2.2.8.1/lib/rack/sendfile.rb:110:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.7.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/ssl.rb:77:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.7.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/actionpack-7.0.8.1/lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.7.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/rack-cors-2.0.1/lib/rack/cors.rb:102:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.7.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/railties-7.0.8.1/lib/rails/engine.rb:530:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.7.1/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.2/lib/puma/configuration.rb:272:in `call'
/app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.2/lib/puma/request.rb:100:in `block in handle_request'
/app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:378:in `with_force_shutdown'
/app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.2/lib/puma/request.rb:99:in `handle_request'
/app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.2/lib/puma/server.rb:464:in `process_client'
/app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.2/lib/puma/server.rb:245:in `block in run'
/app/vendor/bundle/ruby/3.3.0/gems/puma-6.4.2/lib/puma/thread_pool.rb:155:in `block in spawn_thread'
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.7.1/lib/new_relic/agent/tracer.rb:434:in `block (2 levels) in thread_block_with_current_transaction'
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.7.1/lib/new_relic/agent/tracer.rb:357:in `capture_segment_error'
/app/vendor/bundle/ruby/3.3.0/gems/newrelic_rpm-9.7.1/lib/new_relic/agent/tracer.rb:433:in `block in thread_block_with_current_transaction'

```

</p>
</details> 
 

## Steps to Reproduce

Set in test header['Content-Type'] = :"text/html"

## Your Environment

Rails 7.0
Ruby 3.3

### PR DESCRIPTION
**Pull request by fallwith**
These changes introduce hardening to the logic that determines whether or not to inject the browser agent script tag.

In particular, the following 2 issues have been addressed:

1. If either `#traced_call` or `#should_instrument?` encounter any exceptions, these exceptions should be handled and logged without impacting the observed web application.
2. Allow a response headers hash to use symbols for values.

Closes #2462

### CODE REVIEW

**Comment by fallwith** [comment]
NOTE to @kaylareopelle and @hannahramadan: I was worried about introducing performance overhead while supporting hash values as symbols. After some benchmarking, the solution I came up with is to use `#match?` which is defined on both `Symbol` and `String`. The switch to using `#match?` should actually introduce a small performance boost to all existing users, while also adding support for hash-values-as-symbols users.

Here is the benchmarking code in question:

```ruby
require 'benchmark'

SYMBOLS = { :'an/example' => :'a/value',
            :'another-example' => :'another-value',
            :content_type => :'text/html',
            :traceparent => :'00-da8bc8cc6d062849b0efcf3c169afb5a-7d3efb1b173fecfa-01',
            :tracestate => :'33@nr=0-0-33-2827902-7d3efb1b173fecfa-e8b91a159289ff74-1-1.234567-1518469636035' }

STRINGS = SYMBOLS.each_with_object({}) { |(k,v), h| h[k.to_s] = v.to_s }
TEXT_HTML = 'text/html'
TEXT_HTML_PATTERN = %r{text/html}.freeze
TIMES = 1_000_000

puts 'Finding a speedy way to test symbol text inclusion...'

Benchmark.bm do |x|
  x.report 'baseline' do
    TIMES.times do
      # use STRINGS twice, as SYMBOLS will error out
      STRINGS.each { |k, v| STRINGS[k].include?(TEXT_HTML) }
      STRINGS.each { |k, v| STRINGS[k].include?(TEXT_HTML) }
    end
  end

  x.report '#to_s' do
    TIMES.times do
      SYMBOLS.each { |k, v| SYMBOLS[k].to_s.include?(TEXT_HTML) }
      STRINGS.each { |k, v| STRINGS[k].to_s.include?(TEXT_HTML) }
    end
  end

  x.report '#match? with pattern' do
    TIMES.times do
      SYMBOLS.each { |k, v| SYMBOLS[k].match?(TEXT_HTML_PATTERN) }
      STRINGS.each { |k, v| STRINGS[k].match?(TEXT_HTML_PATTERN) }
    end
  end

  x.report '#match? with string' do
    TIMES.times do
      SYMBOLS.each { |k, v| SYMBOLS[k].match?(TEXT_HTML) }
      STRINGS.each { |k, v| STRINGS[k].match?(TEXT_HTML) }
    end
  end
end
```

**Review by kaylareopelle — COMMENTED** [review]
I really like these updates, @fallwith. Especially with the performance boost! 

I think we might want a changelog entry for this. What do you think?

File: test/new_relic/rack/browser_monitoring_test.rb [hunk 1]
```diff
@@ -222,6 +222,32 @@ def test_content_length_set_when_response_is_nil
       assert_equal '0', headers['Content-Length']
     end
 
+    # introduce an exception in the middle of #traced_call and verify that
```
Comment (kaylareopelle) [inline test/new_relic/rack/browser_monitoring_test.rb:225]: For documentation's sake, what do you think about adding a test with a Content-Type header that's a symbol?

**Comment by fallwith** [comment]
> I really like these updates, @fallwith. Especially with the performance boost!
> 
> I think we might want a changelog entry for this. What do you think?

Sounds good. Let me figure out what's going on with these unit tests that aren't happy with the new `rescue` blocks and then I'll circle back with an entry that matches whatever the code that passes the tests ends up looking like.

File: test/new_relic/rack/browser_monitoring_test.rb (hunk 1 above)
Comment (fallwith) [reply test/new_relic/rack/browser_monitoring_test.rb]: Added with [5ef2fbd](https://github.com/newrelic/newrelic-ruby-agent/pull/2465/commits/5ef2fbde9850476c902e7106df51de8acb041be9)

**Comment by fallwith** [comment]
> > I really like these updates, @fallwith. Especially with the performance boost!
> > I think we might want a changelog entry for this. What do you think?
> 
> Sounds good. Let me figure out what's going on with these unit tests that aren't happy with the new `rescue` blocks and then I'll circle back with an entry that matches whatever the code that passes the tests ends up looking like.

Ah ok. I was rescuing too far up the chain. We want legitimate issues to be surfaced and not rescued. With the latest commit we're still rescuing all headers parsing and other determinations of whether the browser agent should be inserted. The tests should pass now and a changelog entry has been added.

File: lib/new_relic/rack/browser_monitoring.rb [hunk 2]
```diff
@@ -23,8 +23,8 @@ class BrowserMonitoring < AgentMiddleware
       CONTENT_TYPE = 'Content-Type'.freeze
       CONTENT_DISPOSITION = 'Content-Disposition'.freeze
       CONTENT_LENGTH = 'Content-Length'.freeze
-      ATTACHMENT = 'attachment'.freeze
-      TEXT_HTML = 'text/html'.freeze
+      ATTACHMENT = /attachment/.freeze
+      TEXT_HTML = %r{text/html}.freeze
```
Comment (hannahramadan) [inline lib/new_relic/rack/browser_monitoring.rb:27]: TIL about %r{}! Nice

File: lib/new_relic/rack/browser_monitoring.rb [hunk 3]
```diff
@@ -65,6 +65,10 @@ def should_instrument?(env, status, headers)
           html?(headers) &&
           !attachment?(headers) &&
           !streaming?(env, headers)
+      rescue StandardError => e
```
Comment (hannahramadan) [inline lib/new_relic/rack/browser_monitoring.rb:68]: Could do `rescue => e` here but as I'm also cool with it as-is!

**Review by hannahramadan — APPROVED** [review]
ser bra ut!

File: lib/new_relic/rack/browser_monitoring.rb (hunk 3 above)
Comment (fallwith) [reply lib/new_relic/rack/browser_monitoring.rb:68]: Aha! You and I were talking about this one recently and I was trying to figure out where my knowledge of a related best practice was coming from.

It turns out that RuboCop prefers it this way, with a named class. See [Style/RescueStandardError](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/RescueStandardError). For some reason this project has (temporarily?) disabled that cop, but I still heed its advice and would prefer to stick with a named class.

File: lib/new_relic/rack/browser_monitoring.rb (hunk 2 above)
Comment (fallwith) [reply lib/new_relic/rack/browser_monitoring.rb:27]: It's most useful for cases like this where there's a literal forward slash character involved in the pattern.
