### PR TITLE
Thread Profile / Backtrace 3.4.0 fixes

### LINKED ISSUE #2992: Update `BacktraceNode` and `ThreadProfile` classes for Ruby 3.4
The `BacktraceNode` class has a regex that relies on the pre-Ruby 3.4 backtrace syntax: 

https://github.com/newrelic/newrelic-ruby-agent/blob/92a012836440ea93ed11ccad93807f26099a9184/lib/new_relic/agent/threading/backtrace_node.rb#L126-L129

In Ruby 3.4, this syntax will remove the backtick character and replace it with a single quotation mark. The content within the single quotation mark will become the Class name combined with the method name (ex. `BacktraceNode#parse_backtrace_frame`). 

The new syntax is not compatible with our existing regex.

Update the regex for Ruby 3.4+ compatibility and conditionally apply the regex based on Ruby version.

### PR DESCRIPTION
**Pull request by kaylareopelle**
Closes #2992

CI, passing on the relevant runs: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/12403980066

### CODE REVIEW

File: test/new_relic/agent/threading/backtrace_node_test.rb [hunk 1]
```diff
@@ -7,15 +7,22 @@
 
 module NewRelic::Agent::Threading
   class BacktraceNodeTest < Minitest::Test
-    SINGLE_LINE = "irb.rb:69:in `catch'"
-
     def setup
+      @single_line = ruby_3_4_0_or_above? ? "irb.rb:69:in 'Kernel#catch'" : "irb.rb:69:in `catch'"
```
Comment (hannahramadan) [inline test/new_relic/agent/threading/backtrace_node_test.rb:11]: fun instance variable setup!

**Review by hannahramadan — APPROVED** [review]
Looks great thank you! For tests that use the new methods `ruby_3_4_0_or_above?`, do you think we need to add TODO to remove when 3.3 is dropped similar to the code comment or should the code TODO be enough of a remind to go check out the tests

**Comment by kaylareopelle** [comment]
> Looks great thank you! For tests that use the new methods `ruby_3_4_0_or_above?`, do you think we need to add TODO to remove when 3.3 is dropped similar to the code comment or should the code TODO be enough of a remind to go check out the tests

Great question! If it seems like a TODO would be helpful, I think it's worth including. They're tests that we don't look at often, so I don't think it'd be very bothersome.

**Review by hannahramadan — APPROVED** [review]

**Review by tannalynn — APPROVED** [review]
