### PR TITLE
Prevent undfined method error in Action Controller instrumentation

### LINKED ISSUE #1842: undefined method 'controller_path' errors filling up logs since 8.16.0 upgrade
## Description

There is a long error backtrace getting logged every time an omniauth login failure happens.  We also upgraded to rails 7.0.4.2 along with newrelic 8.16.0.

newrelic 8.15.0 with rails 6.1.7.1 did not produce these errors.

image

## Expected Behavior

No errors in the logs.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

The `failure` method in `omniauth_callbacks_controller.rb` simply has the line `redirect_to root_path`.

## Your Environment

Ruby 3.2.1
Rails 7.0.4.2
newrelic_rpm 8.16.0

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*

### PR DESCRIPTION
**Pull request by tannalynn**
If the action controller instrumentation was being called for a class that didn't respond to `controller_path`, the agent would error when trying to create the metric name for the segment. Now it will always check to make sure that method will work before calling it. I also updated this section to use the safe navigation operator now that we only support ruby 2.4+.

closes #1842

### CODE REVIEW

File: lib/new_relic/agent/instrumentation/action_controller_other_subscriber.rb [hunk 1]
```diff
@@ -27,11 +27,14 @@ def metric_name(name, payload)
         end
 
         def controller_name_for_metric(payload)
+          return unless payload
           # redirect_to
-          return payload[:request].controller_class.controller_path if payload[:request] && payload[:request].controller_class
+          return payload[:request].controller_class.controller_path if payload[:request].respond_to?(:controller_class) && payload[:request]&.controller_class&.respond_to?(:controller_path)
```
Comment (fallwith) [inline lib/new_relic/agent/instrumentation/action_controller_other_subscriber.rb:32]:
```suggestion
          return payload[:request].controller_class.controller_path if payload[:request].respond_to?(:controller_class) && payload[:request].controller_class&.respond_to?(:controller_path)
```

**Review by fallwith — APPROVED** [review]

File: CHANGELOG.md [hunk 2]
```diff
@@ -13,6 +13,11 @@
 
   Previously, the agent sometimes received children of the `NewRelic::Agent::HTTPClients::AbstractRequest` class as an argument when `NewRelic::Agent::Transaction::DistributedTracers#log_request_headers` was called. This caused debug-level log messages that print the request headers to show human-readable Objects (ex. `#<NewRelic::Agent::HTTPClients::HTTPClientRequest:0x00007fd0dda983e0>`) instead of the request headers. Now, the hash of the request headers should always be logged. [PR#1839](https://github.com/newrelic/newrelic-ruby-agent/pull/1839)
 
+- **Bugfix: Undefined method `controller_path` logged in Action Controller Instrumentation**
+
+  Previously, agent could log an error when trying to determine the metric name in the Action Controller instrumentation if the contrller class did not respond to `controller_path`. This has been resolved and the agent will no longer call this method unless the class responds to it. Thank you to @ for letting us know about this issue [PR#1844](https://github.com/newrelic/newrelic-ruby-agent/pull/1844)
```
Comment (kaylareopelle) [inline CHANGELOG.md:18]:
```suggestion
  Previously, the agent could log an error when trying to determine the metric name in the Action Controller instrumentation if the controller class did not respond to `controller_path`. This has been resolved and the agent will no longer call this method unless the class responds to it. Thank you to [@gsar](https://github.com/gsar) for letting us know about this issue. [PR#1844](https://github.com/newrelic/newrelic-ruby-agent/pull/1844)
```

**Review by kaylareopelle — APPROVED** [review]
🦄
