### PR TITLE
Rails v7.1 driven 'rails' / 'rails_prepend' suite updates

### LINKED ISSUE #2243: CI: Rails 7.1 test help Railtie causes multiverse issues owing to "application" not being set
Rails v7.1 came out yesterday and then in the evening our CI system ran some Rails multiverse tests with it and errored out.

See recent GitHub Actions failed suites [here](https://github.com/newrelic/newrelic-ruby-agent/actions/runs/6429649063).

- Our multiverse file `app_rails3_plus.rb` performs `require 'rails/test_help'`
- The Rails test helper Railtie brings in `maintain_test_schema.rb` which calls `application.config`.
- Apparently our multiverse hasn't booted / brought in the app as expected, because `application` is `nil` at `#config` call time and the call errors out.

### LINKED ISSUE #2244: CI: Include Rails Edge in the multiverse Rails suite
Our CI system tests Rails Edge for our unit and environment tests, but not for our multiverse tests.

This is because the multiverse tests currently generate a `Gemfile.0` file with `gem 'rails'` that will instruct Bundler to grab the latest stable release of Rails. No Edge / beta / preview releases will be fetched.

Given that our envfile code has been updated recently to permit `git` syntax in `Gemfile` files, we should update `test/multiverse/suites/rails/Envfile` to have an additional Rails Edge entry on a peer level with the existing `nil` entry.

NOTE that we may want to conditionally include Rails Edge for only Rails 2.7 and above, as we do with Rails Edge testing elsewhere.

### PR DESCRIPTION
**Pull request by fallwith**
Update the multiverse 'rails' suite (which also has content reused by the 'rails_prepend' suite) for Rails v7.1 compatibility

resolves #2243
resolves #2244

### CODE REVIEW

File: lib/new_relic/control/frameworks/rails.rb [hunk 1]
```diff
@@ -10,6 +10,9 @@ module Frameworks
       # Rails specific configuration, instrumentation, environment values,
       # etc.
       class Rails < NewRelic::Control::Frameworks::Ruby
+        INSTALLED_SINGLETON = NewRelic::Agent.config
+        INSTALLED = :@browser_monitoring_installed
```
Comment (kaylareopelle) [inline lib/new_relic/control/frameworks/rails.rb:14]: I really like this refactor. Would you be open to updating the `INSTALLED` constant name to include "browser" in some way? When I was reading the tests, I got a bit confused about what specifically was being installed.

I think `INSTALLED_SINGLETON` is fine as-is, but could be `NEW_RELIC_AGENT_CONFIG` if you wanted to have more specificity there as well.

File: test/multiverse/suites/rails/Envfile [hunk 2]
```diff
@@ -3,6 +3,7 @@
 # frozen_string_literal: true
 
 RAILS_VERSIONS = [
+  ["github: 'rails'", 3.0], # Rails Edge
```
Comment (kaylareopelle) [inline test/multiverse/suites/rails/Envfile:6]: love this, thank you

File: test/multiverse/suites/rails/before_suite.rb [hunk 3]
```diff
@@ -0,0 +1,23 @@
+# This file is distributed under New Relic's license terms.
+# See https://github.com/newrelic/newrelic-ruby-agent/blob/main/LICENSE for complete details.
+# frozen_string_literal: true
+
+# These are hacks to make the 'rails' multiverse test suite compatible with
+# Rails v7.1 released on 2023-10-05.
+#
+# TODO: refactor these out with non-hack replacements as time permits
```
Comment (kaylareopelle) [inline test/multiverse/suites/rails/before_suite.rb:8]: Can you create an issue for this TODO?

File: lib/new_relic/control/frameworks/rails.rb (hunk 1 above)
Comment (fallwith) [reply lib/new_relic/control/frameworks/rails.rb]: Updated the names with [7ca493f](https://github.com/newrelic/newrelic-ruby-agent/pull/2248/commits/7ca493f627d67de4dbf57b1a3f8173995f0a1f59). I'd prefer to keep the "AGENT_CONFIG" part out of the name itself for flexibility. When I first created the constant I envisioned the control class not being particularly concerned with what class is being used for singleton work - just the class's name. By keeping the singleton's name out of the constant name, a different value could be used in future.

File: test/multiverse/suites/rails/before_suite.rb (hunk 3 above)
Comment (fallwith) [reply test/multiverse/suites/rails/before_suite.rb:8]: Done, https://github.com/newrelic/newrelic-ruby-agent/issues/2254

**Review by kaylareopelle — DISMISSED** [review]

File: test/multiverse/suites/rails/Envfile (hunk 2 above)
Comment (fallwith) [reply test/multiverse/suites/rails/Envfile]: I'm glad to hear it! I was super pleased when I realized that the previous work we did on Envfile helpers made this as easy as this.

File: test/multiverse/lib/multiverse/envfile.rb [hunk 4]
```diff
@@ -133,6 +133,34 @@ def serialize?
       @serialize
     end
 
+    # add Rails Edge to the array of gem versions for testing,
+    # unless we're operating in a PR workflow context
+    def prepend_rails_edge(gem_version_array = [])
```
Comment (kaylareopelle) [inline test/multiverse/lib/multiverse/envfile.rb:138]: I'm so glad to see the earlier work on Envfiles could make adding this method a bit easier! I like the implementation.

Even though this is an accurate use of prepend in the English language, I feel a bit uncomfortable with this method name. In Ruby contexts, I equate "prepend" with the "prepend" method, and I don't see that method being called here.

Cueing off the comments surrounding this method, perhaps `unshift_rails_edge` or `add_rails_edge` could be a better fit?

**Review by kaylareopelle — APPROVED** [review]
One non-blocking comment. Approved as-is!

File: test/multiverse/suites/rails/before_suite.rb [hunk 5]
```diff
@@ -0,0 +1,23 @@
...
+if Gem::Version.new(Rails.version) >= Gem::Version.new('7.1.0')
+  # NoMethodError (undefined method `to_ary' for an instance of ActionController::Streaming::Body):
+  # actionpack (7.1.0) lib/action_dispatch/http/response.rb:107:in `to_ary'
+  # actionpack (7.1.0) lib/action_dispatch/http/response.rb:509:in `to_ary'
+  # rack (3.0.8) lib/rack/body_proxy.rb:41:in `method_missing'
+  # rack (3.0.8) lib/rack/etag.rb:32:in `call'
+  # newrelic-ruby-agent/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
+  require 'action_controller/railtie'
+  class ActionController::Streaming::Body
+    def to_ary
```
Comment (tannalynn) [inline test/multiverse/suites/rails/before_suite.rb:19]: Were we able to determine if this was definitely a test only issue? My only concern is if this is an issue that could potentially affect customers

Comment (fallwith) [reply test/multiverse/suites/rails/before_suite.rb:19]: I share your concern. See https://github.com/newrelic/newrelic-ruby-agent/issues/2254 for getting to the bottom of it.

File: test/multiverse/lib/multiverse/envfile.rb (hunk 4 above)
Comment (fallwith) [reply test/multiverse/lib/multiverse/envfile.rb]: Heh. I wanted to avoid confusing non-Rubyists with the naming but used a name that would instead confuse Rubyists. Went with `unshift_rails_edge` in [a63e5cc](https://github.com/newrelic/newrelic-ruby-agent/pull/2248/commits/a63e5ccc5542bc9ab3e31b2a026c1c865317fef5)

**Review by tannalynn — APPROVED** [review]

**Review by kaylareopelle — APPROVED** [review]

File: test/multiverse/lib/multiverse/envfile.rb [hunk 6]
```diff
@@ -133,6 +133,34 @@ def serialize?
       @serialize
     end
 
+    # add Rails Edge to the beginning of the array of gem versions for testing,
+    # unless we're operating in a PR workflow context
+    def unshift_rails_edge(gem_version_array = [])
+      return if ci_for_pr?
+
+      # Unshift Rails Edge (representing the latest GitHub primary branch
```
Comment (hannahramadan) [inline test/multiverse/lib/multiverse/envfile.rb:141]: Very helpful comment! Cool we get to test with the latest now
