### PR TITLE
Bugfix: Record code level metric attributes for private methods

### LINKED ISSUE #1589: "Unable to determine source code info" on instrumenting private methods
## Description

When using add_method_tracer on a private method, this warning is printed to the newrelic log:

```
[2022-11-04 13:54:24 +0000 M1MBP.local (29101)] WARN : Unable to determine source code info for 'Foo', method 'secret_method' - NameError: undefined method `secret_method' for class `#<Class:Foo>'

          klass.method(method_name)
               ^^^^^^^
```

## Expected Behavior
No warning is printed.

## Steps to Reproduce

```ruby
class Foo
  include NewRelic::Agent::MethodTracer

  private

  def secret_method
  end
  add_method_tracer :secret_method
end
```

## Your Environment
newrelic 8.12.0
ruby 3.1.2

## Additional context

instance_methods here - 
https://github.com/newrelic/newrelic-ruby-agent/blob/9a8d24072f84ac971302220ae2473a49d85678ed/lib/new_relic/agent/method_tracer_helpers.rb#L109-L114 doesn't include private methods. Perhaps it should be `(klass.instance_methods + klass.private_instance_methods).include?(method_name)` ?

### PR DESCRIPTION
**Pull request by tannalynn**
_Before contributing, please read our [contributing guidelines](https://github.com/newrelic/newrelic-ruby-agent/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/newrelic/.github/blob/master/CODE_OF_CONDUCT.md)._

# Overview
This resolves the error caused by setting add_method_tracer on a private method. Previously, the agent would fail to check the private method as an instance method because it was not included in the instance_methods array, so it attempted to record it as a class method, resulting in the following error in the logs
```
WARN : Unable to determine source code info for 'Example', method 'private_method' - NameError: undefined method 'private_method' for class '#<Class:Example>'
```

resolves #1589 Thanks @jdelStrother for the suggested fix!

Submitter Checklist:
- [ ] Include a link to the related GitHub issue, if applicable
- [ ] Include a security review link, if applicable

# Testing
The agent includes a suite of unit and functional tests which should be used to
verify your changes don't break existing functionality. These tests will run with 
GitHub Actions when a pull request is made. More details on running the tests locally can be found 
[here for our unit tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/README.md), 
and [here for our functional tests](https://github.com/newrelic/newrelic-ruby-agent/blob/main/test/multiverse/README.md).
For most contributions it is strongly recommended to add additional tests which
exercise your changes. 

# Reviewer Checklist
- [ ] Perform code review
- [ ] Add performance label
- [ ] Perform appropriate level of performance testing
- [ ] Confirm all checks passed
- [ ] Add version label prior to acceptance

### CODE REVIEW

File: lib/new_relic/agent/method_tracer_helpers.rb [hunk 1]
```diff
@@ -106,7 +106,7 @@ def namespace_and_location(object, method_name)
         klass = object.singleton_class? ? klassify_singleton(object) : object
         name = klass.name || '(Anonymous)'
         is_class_method = false
-        method = if klass.instance_methods.include?(method_name)
+        method = if (klass.instance_methods + klass.private_instance_methods).include?(method_name)
```
Comment (tannalynn) [inline lib/new_relic/agent/method_tracer_helpers.rb:109]: I ran some microbenchmarking on different ways to combine arrays, and `+` was the fastest one, but not by much, all but one said `same-ish: difference falls within error`

**Review by fallwith — APPROVED** [review]

**Comment by jcrisp** [comment]
Hi, I am receiving a similar warning
WARN : Unable to determine source code info for 'XYZController', method 'index'.
The controller doesn't have a method for 'index' but it does have an 'index' view and it is in routes.rb. The method is not required on the Controller in this case, and this has always worked in Rails. My newrelic_agent.log is full of this warning. Can this check be fixed or disabled? Thanks
